#!/bin/bash
for schema in $(ls -d examples/* | xargs -n 1 basename)
do
  if [ -f "schemas/$schema.json" ]
  then
    # example files are lists of examples, so we need a schema to unwrap the array
    schema_id="https://github.com/mbta/schemas/blob/main/schemas/$schema.json"
    array_schema="
    {
      'type':'array',
      'contains':{
        '$ref':'$schema_id'
      }
    }
    "
    echo "$array_schema" | npx ajv validate --spec=draft2020 -s /dev/stdin -r schemas/$schema.json -d "examples/$schema/*.json"
  fi
done
