name: CI

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        id: configure
      - name: Install
        run: yarn
      - name: Check
        run: yarn ci
